"default.cpp"(1,1):vectorFonts.push_back("fonts\\1Row");
"default.cpp"(108,1):vectorFonts.push_back("fonts\\3D-ASCII");
"default.cpp"(215,1):vectorFonts.push_back("fonts\\4Max");
"default.cpp"(322,1):vectorFonts.push_back("fonts\\Acrobatic");
"default.cpp"(429,1):vectorFonts.push_back("fonts\\Alligator2");
"default.cpp"(536,1):vectorFonts.push_back("fonts\\Alpha");
"default.cpp"(643,1):vectorFonts.push_back("fonts\\AMC AAA01");
"default.cpp"(750,1):vectorFonts.push_back("fonts\\AMC Razor2");
"default.cpp"(857,1):vectorFonts.push_back("fonts\\AMC Thin");
"default.cpp"(964,1):vectorFonts.push_back("fonts\\ANSI Regular");
"default.cpp"(1071,1):vectorFonts.push_back("fonts\\ANSI Shadow");
"default.cpp"(1178,1):vectorFonts.push_back("fonts\\ASCII New Roman");
"default.cpp"(1286,1):vectorFonts.push_back("fonts\\Avatar");
"default.cpp"(1393,1):vectorFonts.push_back("fonts\\B1FF");
"default.cpp"(1398,1):vectorFonts.push_back("fonts\\Banner3");
"default.cpp"(1505,1):vectorFonts.push_back("fonts\\Bear");
"default.cpp"(1613,1):vectorFonts.push_back("fonts\\Big Money-ne");
"default.cpp"(1720,1):vectorFonts.push_back("fonts\\Big Money-nw");
"default.cpp"(1827,1):vectorFonts.push_back("fonts\\Big Money-se");
"default.cpp"(1934,1):vectorFonts.push_back("fonts\\Big Money-sw");
"default.cpp"(2041,1):vectorFonts.push_back("fonts\\Bigfig");
"default.cpp"(2149,1):vectorFonts.push_back("fonts\\Blocks");
"default.cpp"(2256,1):vectorFonts.push_back("fonts\\Bloody");
"default.cpp"(2363,1):vectorFonts.push_back("fonts\\Bright");
"default.cpp"(2470,1):vectorFonts.push_back("fonts\\Bulbhead");
"default.cpp"(2578,1):vectorFonts.push_back("fonts\\Caligraphy");
"default.cpp"(2685,1):vectorFonts.push_back("fonts\\Calvin S");
"default.cpp"(2792,1):vectorFonts.push_back("fonts\\Cards");
"default.cpp"(2797,1):vectorFonts.push_back("fonts\\Catwalk");
"default.cpp"(2904,1):vectorFonts.push_back("fonts\\Chiseled");
"default.cpp"(3011,1):vectorFonts.push_back("fonts\\Cola");
"default.cpp"(3119,1):vectorFonts.push_back("fonts\\Contrast");
"default.cpp"(3226,1):vectorFonts.push_back("fonts\\Crawford2");
"default.cpp"(3333,1):vectorFonts.push_back("fonts\\Crazy");
"default.cpp"(3440,1):vectorFonts.push_back("fonts\\Cricket");
"default.cpp"(3547,1):vectorFonts.push_back("fonts\\Cybermedium");
"default.cpp"(3654,1):vectorFonts.push_back("fonts\\Dancing Font");
"default.cpp"(3762,1):vectorFonts.push_back("fonts\\Decimal");
"default.cpp"(3767,1):vectorFonts.push_back("fonts\\Delta Corps Priest 1");
"default.cpp"(3874,1):vectorFonts.push_back("fonts\\Doom");
"default.cpp"(3981,1):vectorFonts.push_back("fonts\\Double Shorts");
"default.cpp"(4088,1):vectorFonts.push_back("fonts\\Efti Wall");
"default.cpp"(4195,1):vectorFonts.push_back("fonts\\Efti Water");
"default.cpp"(4302,1):vectorFonts.push_back("fonts\\Electronic");
"default.cpp"(4409,1):vectorFonts.push_back("fonts\\Elite");
"default.cpp"(4516,1):vectorFonts.push_back("fonts\\Epic");
"default.cpp"(4623,1):vectorFonts.push_back("fonts\\Filter");
"default.cpp"(4731,1):vectorFonts.push_back("fonts\\Fire Font-k");
"default.cpp"(4839,1):vectorFonts.push_back("fonts\\Fire Font-s");
"default.cpp"(4947,1):vectorFonts.push_back("fonts\\Flower Power");
"default.cpp"(5055,1):vectorFonts.push_back("fonts\\Four Tops");
"default.cpp"(5162,1):vectorFonts.push_back("fonts\\Fun Face");
"default.cpp"(5270,1):vectorFonts.push_back("fonts\\Fun Faces");
"default.cpp"(5378,1):vectorFonts.push_back("fonts\\Fuzzy");
"default.cpp"(5485,1):vectorFonts.push_back("fonts\\Ghost");
"default.cpp"(5593,1):vectorFonts.push_back("fonts\\Ghoulish");
"default.cpp"(5701,1):vectorFonts.push_back("fonts\\Gothic");
"default.cpp"(5808,1):vectorFonts.push_back("fonts\\Graffiti");
"default.cpp"(5916,1):vectorFonts.push_back("fonts\\Greek");
"default.cpp"(6023,1):vectorFonts.push_back("fonts\\Hex");
"default.cpp"(6028,1):vectorFonts.push_back("fonts\\Horizontal Right");
"default.cpp"(6135,1):vectorFonts.push_back("fonts\\Impossible");
"default.cpp"(6242,1):vectorFonts.push_back("fonts\\Isometric1");
"default.cpp"(6349,1):vectorFonts.push_back("fonts\\Italic");
"default.cpp"(6456,1):vectorFonts.push_back("fonts\\Jacky");
"default.cpp"(6567,1):vectorFonts.push_back("fonts\\JS Bracket Letters");
"default.cpp"(6674,1):vectorFonts.push_back("fonts\\JS Capital Curves");
"default.cpp"(6782,1):vectorFonts.push_back("fonts\\Kban");
"default.cpp"(6889,1):vectorFonts.push_back("fonts\\Konto Slant");
"default.cpp"(6997,1):vectorFonts.push_back("fonts\\LCD");
"default.cpp"(7104,1):vectorFonts.push_back("fonts\\Lil Devil");
"default.cpp"(7211,1):vectorFonts.push_back("fonts\\listaDeFuentes");
"default.cpp"(7216,1):vectorFonts.push_back("fonts\\Lockergnome");
"default.cpp"(7323,1):vectorFonts.push_back("fonts\\Maxfour");
"default.cpp"(7430,1):vectorFonts.push_back("fonts\\Merlin1");
"default.cpp"(7538,1):vectorFonts.push_back("fonts\\Modular");
"default.cpp"(7646,1):vectorFonts.push_back("fonts\\Morse");
"default.cpp"(7651,1):vectorFonts.push_back("fonts\\Muzzle");
"default.cpp"(7759,1):vectorFonts.push_back("fonts\\Nancyj-Fancy");
"default.cpp"(7866,1):vectorFonts.push_back("fonts\\Nancyj");
"default.cpp"(7973,1):vectorFonts.push_back("fonts\\Ogre");
"default.cpp"(8080,1):vectorFonts.push_back("fonts\\Patorjk's Cheese");
"default.cpp"(8180,1):vectorFonts.push_back("fonts\\Patorjk-HeX");
"default.cpp"(8280,1):vectorFonts.push_back("fonts\\Peaks Slant");
"default.cpp"(8387,1):vectorFonts.push_back("fonts\\Rammstein");
"default.cpp"(8495,1):vectorFonts.push_back("fonts\\Rectangles");
"default.cpp"(8602,1):vectorFonts.push_back("fonts\\Relief");
"default.cpp"(8709,1):vectorFonts.push_back("fonts\\Rot13");
"default.cpp"(8714,1):vectorFonts.push_back("fonts\\Rotated");
"default.cpp"(8822,1):vectorFonts.push_back("fonts\\Rozzo");
"default.cpp"(8929,1):vectorFonts.push_back("fonts\\SL Script");
"default.cpp"(9036,1):vectorFonts.push_back("fonts\\Slant Relief");
"default.cpp"(9143,1):vectorFonts.push_back("fonts\\Small Isometric1");
"default.cpp"(9250,1):vectorFonts.push_back("fonts\\Small Keyboard");
"default.cpp"(9357,1):vectorFonts.push_back("fonts\\Soft");
"default.cpp"(9465,1):vectorFonts.push_back("fonts\\Stacey");
"default.cpp"(9572,1):vectorFonts.push_back("fonts\\Star Strips");
"default.cpp"(9680,1):vectorFonts.push_back("fonts\\Star Wars");
"default.cpp"(9787,1):vectorFonts.push_back("fonts\\Stick Letters");
"default.cpp"(9894,1):vectorFonts.push_back("fonts\\Stronger Than All");
"default.cpp"(10001,1):vectorFonts.push_back("fonts\\Sub-Zero");
"default.cpp"(10108,1):vectorFonts.push_back("fonts\\Swamp Land");
"default.cpp"(10216,1):vectorFonts.push_back("fonts\\Sweet");
"default.cpp"(10324,1):vectorFonts.push_back("fonts\\Tengwar");
"default.cpp"(10431,1):vectorFonts.push_back("fonts\\The Edge");
"default.cpp"(10538,1):vectorFonts.push_back("fonts\\Thin");
"default.cpp"(10645,1):vectorFonts.push_back("fonts\\THIS");
"default.cpp"(10752,1):vectorFonts.push_back("fonts\\Ticks");
"default.cpp"(10859,1):vectorFonts.push_back("fonts\\Train");
"default.cpp"(10966,1):vectorFonts.push_back("fonts\\Trek");
"default.cpp"(11073,1):vectorFonts.push_back("fonts\\Twisted");
"default.cpp"(11181,1):vectorFonts.push_back("fonts\\Two Point");
"default.cpp"(11288,1):vectorFonts.push_back("fonts\\Varsity");
"default.cpp"(11395,1):vectorFonts.push_back("fonts\\Wet Letter");
"default.cpp"(11503,1):vectorFonts.push_back("fonts\\Whimsy");
