vectorFonts.push_back("Wavy");
if(font=="Wavy"){
   nl = "@"
d = p1 = ap2 = $eight = Height_nd = en = p6_defSmuMod = Comm = 
    if ((charNumber == 1) || (character == "" )) { oneChar ="$$@$$@$$@$$" };
    if ((charNumber == 2) || (character == "!" )) { oneChar ="$ @|$@o$@$ " };
    if ((charNumber == 3) || (character == """ )) { oneChar =" $ @||$@ $ @ $ " };
    if ((charNumber == 4) || (character == "#" )) { oneChar ="     $ @ _/_/_$@-/-/-$ @    $  " };
    if ((charNumber == 5) || (character == "$" )) { oneChar ="  $ @(I`$@.I)$@  $ " };
    if ((charNumber == 6) || (character == "%" )) { oneChar ="  $@o/$@/o$@ $ " };
    if ((charNumber == 7) || (character == "&" )) { oneChar ="_$ @\)$@(X$@  $" };
    if ((charNumber == 8) || (character == "'" )) { oneChar ="$ @|$@$ @$ " };
    if ((charNumber == 9) || (character == "(" )) { oneChar =" /$@($ @ \$@  $" };
    if ((charNumber == 10) || (character == ")" )) { oneChar ="\$ @ )$@/$ @$  " };
    if ((charNumber == 11) || (character == "*" )) { oneChar ="   $ @_\/_$@ /\$ @  $  " };
    if ((charNumber == 12) || (character == "+" )) { oneChar ="   $ @$_|_$@ $|$ @  $  " };
    if ((charNumber == 13) || (character == "," )) { oneChar ="$ @$ @o$@/$" };
    if ((charNumber == 14) || (character == "-" )) { oneChar ="  $ @$__$@  $ @  $ " };
    if ((charNumber == 15) || (character == "." )) { oneChar ="$ @$ @o$@$ " };
    if ((charNumber == 16) || (character == "/" )) { oneChar ="  $@ /$@/$ @$  " };
    if ((charNumber == 17) || (character == "0" )) { oneChar =" _$  @(.\$ @ \_)$@   $ " };
    if ((charNumber == 18) || (character == "1" )) { oneChar ="  $  @/($  @ _)_$@    $" };
    if ((charNumber == 19) || (character == "2" )) { oneChar ="_$ @ )$@/_$@  $" };
    if ((charNumber == 20) || (character == "3" )) { oneChar ="_$ @_)$@_)$@ $ " };
    if ((charNumber == 21) || (character == "4" )) { oneChar ="   $ @/_(_$@   )$@   $ " };
    if ((charNumber == 22) || (character == "5" )) { oneChar ="__$ @)_$ @ _)$@  $ " };
    if ((charNumber == 23) || (character == "6" )) { oneChar =" _$  @(__$ @ \_)$@   $ " };
    if ((charNumber == 24) || (character == "7" )) { oneChar ="__$ @  )$@ ($ @  $ " };
    if ((charNumber == 25) || (character == "8" )) { oneChar =" _$ @(_)$@(_)$@  $ " };
    if ((charNumber == 26) || (character == "9" )) { oneChar =" _$  @(_\$ @  _)$@   $ " };
    if ((charNumber == 27) || (character == ":" )) { oneChar ="$ @o$@o$@$ " };
    if ((charNumber == 28) || (character == ";" )) { oneChar ="$ @o$@o$@/$" };
    if ((charNumber == 29) || (character == "<" )) { oneChar ="$ @/$@\$@$ " };
    if ((charNumber == 30) || (character == "=" )) { oneChar =" $ @__$@--$@ $ " };
    if ((charNumber == 31) || (character == ">" )) { oneChar ="$ @\$@/$@$ " };
    if ((charNumber == 32) || (character == "?" )) { oneChar ="_$ @ )$@o$ @ $ " };
    if ((charNumber == 33) || (character == "@" )) { oneChar ="  ___$ @ / _ )$@( (_($ @ \___/$" };
    if ((charNumber == 34) || (character == "A" )) { oneChar ="  _$ @ /_)$@/ /$ @  $  " };
    if ((charNumber == 35) || (character == "B" )) { oneChar =" __$ @ )_)$@/__)$@   $ " };
    if ((charNumber == 36) || (character == "C" )) { oneChar ="  _$ @ / `$@(_.$ @   $ " };
    if ((charNumber == 37) || (character == "D" )) { oneChar =" __$ @ ) )$@/_/$ @  $  " };
    if ((charNumber == 38) || (character == "E" )) { oneChar =" ___$@ )_$ @(__$ @   $ " };
    if ((charNumber == 39) || (character == "F" )) { oneChar =" ___$@ )_$ @($   @ $   " };
    if ((charNumber == 40) || (character == "G" )) { oneChar ="  _$ @ / _$@(__/$@   $ " };
    if ((charNumber == 41) || (character == "H" )) { oneChar ="   $ @ )_)$@( ($ @   $ " };
    if ((charNumber == 42) || (character == "I" )) { oneChar =" ___$@  )$ @_(_$ @   $ " };
    if ((charNumber == 43) || (character == "J" )) { oneChar ="___$ @  ($ @\__)$@   $ " };
    if ((charNumber == 44) || (character == "K" )) { oneChar ="    $@ )_/$@/  )$@   $ " };
    if ((charNumber == 45) || (character == "L" )) { oneChar ="  $ @ )$ @(__$@  $ " };
    if ((charNumber == 46) || (character == "M" )) { oneChar ="    $ @ )\/)$@(  ($ @    $ " };
    if ((charNumber == 47) || (character == "N" )) { oneChar ="    $ @ )\ )$@(  ($ @    $ " };
    if ((charNumber == 48) || (character == "O" )) { oneChar ="  _$ @ / )$@(_/$ @  $  " };
    if ((charNumber == 49) || (character == "P" )) { oneChar =" __$ @ )_)$@/$   @$    " };
    if ((charNumber == 50) || (character == "Q" )) { oneChar ="  _$ @ / )$@(_X$ @     " };
    if ((charNumber == 51) || (character == "R" )) { oneChar =" __$ @ )_)$@/ \$ @  $  " };
    if ((charNumber == 52) || (character == "S" )) { oneChar ="  __$ @ (_ `$@.__)$ @   $  " };
    if ((charNumber == 53) || (character == "T" )) { oneChar ="___$@ )$ @($  @ $  " };
    if ((charNumber == 54) || (character == "U" )) { oneChar ="     @ / /$@(_/$ @  $  " };
    if ((charNumber == 55) || (character == "V" )) { oneChar ="    $@\  /$@ \/$ @  $  " };
    if ((charNumber == 56) || (character == "W" )) { oneChar ="       $@\  X  /$@ \/ \/$ @    $   " };
    if ((charNumber == 57) || (character == "X" )) { oneChar =" $ @(/$@/)$@ $ " };
    if ((charNumber == 58) || (character == "Y" )) { oneChar ="    @\_)$@ /$ @ $  " };
    if ((charNumber == 59) || (character == "Z" )) { oneChar ="__$@ /$@/_$@ $ " };
    if ((charNumber == 60) || (character == "[" )) { oneChar =" _$@|$ @|_$@ $ " };
    if ((charNumber == 61) || (character == "\" )) { oneChar ="$  @\$ @ \$@  $" };
    if ((charNumber == 62) || (character == "]" )) { oneChar ="_$ @ |$@_|$@ $ " };
    if ((charNumber == 63) || (character == "^" )) { oneChar =" $ @/\$@ $ @ $ " };
    if ((charNumber == 64) || (character == "_" )) { oneChar =" $ @ $ @ $ @__$" };
    if ((charNumber == 65) || (character == "`" )) { oneChar ="$ @\$@$ @$ " };
    if ((charNumber == 66) || (character == "a" )) { oneChar ="  $ @ _$ @(_($@  $ " };
    if ((charNumber == 67) || (character == "b" )) { oneChar ="  $  @( _$ @ )_)$@   $ " };
    if ((charNumber == 68) || (character == "c" )) { oneChar =" $ @ _$@(_$@ $ " };
    if ((charNumber == 69) || (character == "d" )) { oneChar ="   $ @ _ )$@(_($ @  $  " };
    if ((charNumber == 70) || (character == "e" )) { oneChar ="   $ @  _$ @ )_)$@(_$  " };
    if ((charNumber == 71) || (character == "f" )) { oneChar ="  $ @_(_$@  )$@  $ " };
    if ((charNumber == 72) || (character == "g" )) { oneChar ="  $  @ _$  @(_($ @  _)$" };
    if ((charNumber == 73) || (character == "h" )) { oneChar ="  $  @( _$ @ ) )$@   $ " };
    if ((charNumber == 74) || (character == "i" )) { oneChar ="$ @o$@($@$ " };
    if ((charNumber == 75) || (character == "j" )) { oneChar ="$  @o$ @($ @_)$" };
    if ((charNumber == 76) || (character == "k" )) { oneChar ="  $ @( _$@ )\$@  $ " };
    if ((charNumber == 77) || (character == "l" )) { oneChar =" $ @ )$@($ @ $ " };
    if ((charNumber == 78) || (character == "m" )) { oneChar ="    $ @ _ _$ @) ) )$@    $ " };
    if ((charNumber == 79) || (character == "n" )) { oneChar ="  $ @ _$ @) )$@  $ " };
    if ((charNumber == 80) || (character == "o" )) { oneChar ="  $ @ _$ @(_)$@  $ " };
    if ((charNumber == 81) || (character == "p" )) { oneChar ="   $ @  _$ @ )_)$@(  $ " };
    if ((charNumber == 82) || (character == "q" )) { oneChar ="  $  @ _$  @(_($ @   )$" };
    if ((charNumber == 83) || (character == "r" )) { oneChar =" $ @ _$@)$ @$  " };
    if ((charNumber == 84) || (character == "s" )) { oneChar =" $ @ _$@($ @_)$" };
    if ((charNumber == 85) || (character == "t" )) { oneChar ="  $ @_)_$@(_$ @ $  " };
    if ((charNumber == 86) || (character == "u" )) { oneChar ="  $ @  $ @(_($@  $ " };
    if ((charNumber == 87) || (character == "v" )) { oneChar =" $ @ $ @\)$@ $ " };
    if ((charNumber == 88) || (character == "w" )) { oneChar ="    $ @    $ @)_)_)$@    $ " };
    if ((charNumber == 89) || (character == "x" )) { oneChar =" $ @ $ @\)$@(\$" };
    if ((charNumber == 90) || (character == "y" )) { oneChar ="  $  @  $  @(_($ @  _)$" };
    if ((charNumber == 91) || (character == "z" )) { oneChar ="  $  @__$  @  )$ @ (__$" };
    if ((charNumber == 92) || (character == "{" )) { oneChar ="  _$@_|$ @ |_$@  $ " };
    if ((charNumber == 93) || (character == "|" )) { oneChar ="$ @|$@|$@|$" };
    if ((charNumber == 94) || (character == "}" )) { oneChar ="_$  @ |_$@_|$ @ $  " };
    if ((charNumber == 95) || (character == "~" )) { oneChar ="  $ @/\/$@  $ @  $ " };
    if ((charNumber == 96) || (character == "Ä" )) { oneChar =" o_o$@ /_)$@/ /$ @  $  " };
    if ((charNumber == 97) || (character == "Ö" )) { oneChar =" o_o$@ / )$@(_/$ @  $  " };
    if ((charNumber == 98) || (character == "Ü" )) { oneChar ="  o o$@ / /$ @(_/$  @  $   " };
    if ((charNumber == 99) || (character == "ä" )) { oneChar ="o o$@ _ $@(_($@   $" };
    if ((charNumber == 100) || (character == "ö" )) { oneChar ="o o$@ _$ @(_)$@  $ " };
    if ((charNumber == 101) || (character == "ü" )) { oneChar ="o o$@   $@(_($@   $" };
    if ((charNumber == 102) || (character == "ß" )) { oneChar =" __$ @ ) )$@/  )$@   $ " };
    if ((charNumber == 103) || (character == "" )) { oneChar ="$$@$$@$$@$$" };
    if ((charNumber == 104) || (character == "" )) { oneChar ="$ @o$@|$@$ " };
    if ((charNumber == 105) || (character == "" )) { oneChar ="  $ @ |$ @(_`$@ |$ " };
    if ((charNumber == 106) || (character == "" )) { oneChar ="  _$ @_(_`$@ o)_$@   $ " };
    if ((charNumber == 107) || (character == "" )) { oneChar ="  $ @`o'$@' `$@  $ " };
    if ((charNumber == 108) || (character == "" )) { oneChar ="   $  @_\_)_$@--/--$@    $ " };
    if ((charNumber == 109) || (character == "" )) { oneChar ="$ @|$@'$@|$" };
    if ((charNumber == 110) || (character == "" )) { oneChar =" _$@($ @()$@_)$" };
    if ((charNumber == 111) || (character == "" )) { oneChar ="o o$@  $ @  $ @  $ " };
    if ((charNumber == 112) || (character == "" )) { oneChar =" _$ @(C)$@  $ @  $ " };
    if ((charNumber == 113) || (character == "" )) { oneChar =" _ $@(_($@---$@  $ " };
    if ((charNumber == 114) || (character == "" )) { oneChar ="  $@//$@\\$@  $" };
    if ((charNumber == 115) || (character == "" )) { oneChar ="  $ @__$ @  |$@  $ " };
    if ((charNumber == 116) || (character == "" )) { oneChar ="$ @_$@$ @$ " };
    if ((charNumber == 117) || (character == "" )) { oneChar =" _$ @(R)$@  $ @  $ " };
    if ((charNumber == 118) || (character == "" )) { oneChar ="__$@ $ @ $ @ $ " };
    if ((charNumber == 119) || (character == "" )) { oneChar ="O$@$ @$ @$ " };
    if ((charNumber == 120) || (character == "" )) { oneChar ="  $ @_|_$@_|_$@  $ " };
    if ((charNumber == 121) || (character == "" )) { oneChar ="2$@  @  @  " };
    if ((charNumber == 122) || (character == "" )) { oneChar ="3$@$ @$ @$ " };
    if ((charNumber == 123) || (character == "" )) { oneChar ="/$@$ @$ @$ " };
    if ((charNumber == 124) || (character == "" )) { oneChar ="   $ @   $ @ )_)$@/$   " };
    if ((charNumber == 125) || (character == "" )) { oneChar =" __$@(||$@ ||$@  $ " };
    if ((charNumber == 126) || (character == "" )) { oneChar ="$ @o$@$ @$ " };
    if ((charNumber == 127) || (character == "" )) { oneChar ="$ @$ @$ @S$" };
    if ((charNumber == 128) || (character == "" )) { oneChar ="1$@$ @$ @$ " };
    if ((charNumber == 129) || (character == "" )) { oneChar =" _$ @(_)$@---$@  $ " };
    if ((charNumber == 130) || (character == "" )) { oneChar =" $ @\\$@//$@ $ " };
    if ((charNumber == 131) || (character == "" )) { oneChar ="  $@1/$@/4$@ $ " };
    if ((charNumber == 132) || (character == "" )) { oneChar ="  $@1/$@/2$@ $ " };
    if ((charNumber == 133) || (character == "" )) { oneChar ="  $@3/$@/4$@ $ " };
    if ((charNumber == 134) || (character == "" )) { oneChar =" $ @ o$@(_$@ $ " };
    if ((charNumber == 135) || (character == "" )) { oneChar ="  \$ @ /_)$@/ /$ @  $  " };
    if ((charNumber == 136) || (character == "" )) { oneChar ="  _/$@ /_)$@/ /$ @  $  " };
    if ((charNumber == 137) || (character == "" )) { oneChar ="  /\$@ /_)$@/ /$ @  $  " };
    if ((charNumber == 138) || (character == "" )) { oneChar =" /\/$@ /_)$@/ /$ @  $  " };
    if ((charNumber == 139) || (character == "" )) { oneChar =" o_o$@ /_)$@/ /$ @  $  " };
    if ((charNumber == 140) || (character == "" )) { oneChar ="  O$ @ /_)$@/ /$ @  $  " };
    if ((charNumber == 141) || (character == "" )) { oneChar ="  ____$@ /_)_$ @/ /__$ @     $ " };
    if ((charNumber == 142) || (character == "" )) { oneChar ="  _$ @ / `$@(_.$ @ S$  " };
    if ((charNumber == 143) || (character == "" )) { oneChar =" _\_$@ )_$ @(__$ @   $ " };
    if ((charNumber == 144) || (character == "" )) { oneChar =" _/_$@ )_$ @(__$ @   $ " };
    if ((charNumber == 145) || (character == "" )) { oneChar =" _/\$@ )_$ @(__$ @   $ " };
    if ((charNumber == 146) || (character == "" )) { oneChar =" o_o$@ )_$ @(__$ @   $ " };
    if ((charNumber == 147) || (character == "" )) { oneChar =" _\_$@  )$ @_(_$ @   $ " };
    if ((charNumber == 148) || (character == "" )) { oneChar =" _/_$@  )$ @_(_$ @   $ " };
    if ((charNumber == 149) || (character == "" )) { oneChar =" _/\$@  )$ @_(_$ @   $ " };
    if ((charNumber == 150) || (character == "" )) { oneChar =" o_o$@  )$ @_(_$ @     " };
    if ((charNumber == 151) || (character == "" )) { oneChar =" __$ @_)_)$@/_/$ @  $  " };
    if ((charNumber == 152) || (character == "" )) { oneChar ="  /\/$@ )\ )$@(  ($ @    $ " };
    if ((charNumber == 153) || (character == "" )) { oneChar ="  \$ @ / )$@(_/$ @  $  " };
    if ((charNumber == 154) || (character == "" )) { oneChar ="  _/$@ / )$@(_/$ @  $  " };
    if ((charNumber == 155) || (character == "" )) { oneChar ="  /\$@ / )$@(_/$ @  $  " };
    if ((charNumber == 156) || (character == "" )) { oneChar =" /\/$@ / )$@(_/$ @  $  " };
    if ((charNumber == 157) || (character == "" )) { oneChar =" o_o$@ / )$@(_/$ @  $  " };
    if ((charNumber == 158) || (character == "" )) { oneChar ="$ @X$@$ @$ " };
    if ((charNumber == 159) || (character == "" )) { oneChar ="  _$ @ //)$@(//$ @  $  " };
    if ((charNumber == 160) || (character == "" )) { oneChar ="  \$ @ / /$@(_/$ @  $  " };
    if ((charNumber == 161) || (character == "" )) { oneChar ="   /$@ / /$@(_/$ @  $  " };
    if ((charNumber == 162) || (character == "" )) { oneChar ="  /\$@ / /$@(_/$ @  $  " };
    if ((charNumber == 163) || (character == "" )) { oneChar ="  o o$@ / /$ @(_/$  @  $   " };
    if ((charNumber == 164) || (character == "" )) { oneChar =" /$ @\_)$@ /$ @ $  " };
    if ((charNumber == 165) || (character == "" )) { oneChar ="( _$ @ )_)$@($   @ $   " };
    if ((charNumber == 166) || (character == "" )) { oneChar ="  __$ @  ) )$@ /  )$@    $ " };
    if ((charNumber == 167) || (character == "" )) { oneChar =" \$ @ _ $@(_($@   $" };
    if ((charNumber == 168) || (character == "" )) { oneChar =" /$ @ _ $@(_($@   $" };
    if ((charNumber == 169) || (character == "" )) { oneChar =" /\$@ _ $@(_($@   $" };
    if ((charNumber == 170) || (character == "" )) { oneChar ="/\/$@ _ $@(_($@   $" };
    if ((charNumber == 171) || (character == "" )) { oneChar ="o o$@ _ $@(_($@   $" };
    if ((charNumber == 172) || (character == "" )) { oneChar =" O$ @ _ $@(_($@   $" };
    if ((charNumber == 173) || (character == "" )) { oneChar ="     $ @  _ _$ @ _ )_)$@(_(_$  " };
    if ((charNumber == 174) || (character == "" )) { oneChar =" $ @ _$@(_$@ S$" };
    if ((charNumber == 175) || (character == "" )) { oneChar =" \$  @  _$ @ )_)$@(_$  " };
    if ((charNumber == 176) || (character == "" )) { oneChar ="  /$ @  _$ @ )_)$@(_$  " };
    if ((charNumber == 177) || (character == "" )) { oneChar =" /\$ @  _ $@ )_)$@(_$  " };
    if ((charNumber == 178) || (character == "" )) { oneChar =" o o$@  _ $@ )_)$@(_$  " };
    if ((charNumber == 179) || (character == "" )) { oneChar ="$ @\$@($@ $" };
    if ((charNumber == 180) || (character == "" )) { oneChar ="$ @/$@($@ $" };
    if ((charNumber == 181) || (character == "" )) { oneChar =" $ @/\$@($ @ $ " };
    if ((charNumber == 182) || (character == "" )) { oneChar =" $ @oo$@($ @ $ " };
    if ((charNumber == 183) || (character == "" )) { oneChar ="  X$ @ _ )$@(_($ @   $ " };
    if ((charNumber == 184) || (character == "" )) { oneChar ="/\/$@ _$ @) )$@  $ " };
    if ((charNumber == 185) || (character == "" )) { oneChar =" \$ @ _$ @(_)$@  $ " };
    if ((charNumber == 186) || (character == "" )) { oneChar =" /$ @ _$ @(_)$@  $ " };
    if ((charNumber == 187) || (character == "" )) { oneChar =" /\$@ _$ @(_)$@    " };
    if ((charNumber == 188) || (character == "" )) { oneChar ="/\/$@ _$ @(_)$@  $ " };
    if ((charNumber == 189) || (character == "" )) { oneChar ="o o$@ _$ @(_)$@  $ " };
    if ((charNumber == 190) || (character == "" )) { oneChar =" o$ @---$@ o$ @  $ " };
    if ((charNumber == 191) || (character == "" )) { oneChar ="  $ @ _$ @(/)$@  $ " };
    if ((charNumber == 192) || (character == "" )) { oneChar =" \$ @   $@(_($@   $" };
    if ((charNumber == 193) || (character == "" )) { oneChar ="  /$@   $@(_($@   $" };
    if ((charNumber == 194) || (character == "" )) { oneChar =" /\$@   $@(_($@   $" };
    if ((charNumber == 195) || (character == "" )) { oneChar ="o o$@   $@(_($@   $" };
    if ((charNumber == 196) || (character == "" )) { oneChar ="  /$ @   $ @(_($ @  _)$" };
    if ((charNumber == 197) || (character == "" )) { oneChar ="  $  @(_$  @ )_)$@($   " };
    if ((charNumber == 198) || (character == "" )) { oneChar ="o o$ @   $ @(_($ @  _)$" };
}