
ascciTextGen_FLF_to_CPP.exe "fonts\\1Row.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\3D Diagonal.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\3D-ASCII.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\4Max.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Acrobatic.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Alligator2.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Alpha.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\AMC AAA01.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\AMC Razor2.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\AMC Thin.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\ANSI Regular.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\ANSI Shadow.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\ASCII New Roman.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Avatar.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\B1FF.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Banner.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Banner3.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Bear.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Big Money-ne.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Big Money-nw.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Big Money-se.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Big Money-sw.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Big.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Bigfig.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Block.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Blocks.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Bloody.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Bright.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Bulbhead.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Caligraphy.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Calvin S.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Cards.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Catwalk.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Chiseled.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Cola.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Contrast.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Crawford2.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Crazy.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Cricket.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Cybermedium.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Dancing Font.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Decimal.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Delta Corps Priest 1.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Digital.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Doh.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Doom.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Double Shorts.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\DWhistled.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Efti Font.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Efti Wall.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Efti Water.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Electronic.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Elite.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Epic.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Filter.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Fire Font-k.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Fire Font-s.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Flower Power.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Four Tops.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Fun Face.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Fun Faces.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Fuzzy.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Ghost.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Ghoulish.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Gothic.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Graceful.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Graffiti.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Greek.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Hex.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Horizontal Right.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Impossible.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Isometric1.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Italic.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Jacky.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\JS Bracket Letters.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\JS Capital Curves.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Kban.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Konto Slant.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\LCD.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Letters.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Lil Devil.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\listaDeFuentes.txt
ascciTextGen_FLF_to_CPP.exe "fonts\\listfiles.txt
ascciTextGen_FLF_to_CPP.exe "fonts\\Lockergnome.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Maxfour.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Merlin1.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Mini.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Modular.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Morse.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Muzzle.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Nancyj-Fancy.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Nancyj.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Octal.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Ogre.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Patorjk's Cheese.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Patorjk-HeX.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Peaks Slant.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Poison.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Rammstein.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Rectangles.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Relief.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Rot13.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Rotated.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Rozzo.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Shadow.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\SL Script.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Slant Relief.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Slant.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Slide.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Small Isometric1.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Small Keyboard.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Small Shadow.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Small Slant.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Small.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Soft.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Speed.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Stacey.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Standard.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Star Strips.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Star Wars.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Stick Letters.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Stronger Than All.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Sub-Zero.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Swamp Land.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Swan.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Sweet.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Tengwar.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\The Edge.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Thin.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\THIS.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Ticks.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Train.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Trek.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Twisted.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Two Point.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Varsity.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Wavy.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Wet Letter.flf"
ascciTextGen_FLF_to_CPP.exe "fonts\\Whimsy.flf"
